// Checklists detalhados para RDC 216 (Serviços de Alimentação) e RDC 275 (Indústria de Alimentos)

export interface ChecklistItem {
  id: string;
  category: string;
  itemNumber: number;
  title: string;
  description: string;
  requirement: string;
  details: string[];
}

export interface ChecklistCategory {
  id: string;
  name: string;
  description: string;
  items: ChecklistItem[];
}

// RDC 216 - SERVIÇOS DE ALIMENTAÇÃO (Restaurantes, Cantinas, UANs)
export const RDC216_CATEGORIES: ChecklistCategory[] = [
  {
    id: 'rdc216-1',
    name: '1. INSTALAÇÕES E DEPENDÊNCIAS',
    description: 'Estrutura física, limpeza, layout e condições gerais das instalações',
    items: [
      {
        id: 'rdc216-1-1',
        category: '1. INSTALAÇÕES',
        itemNumber: 1,
        title: 'Localização e Acesso',
        description: 'A unidade deve estar localizada em local apropriado, longe de focos de contaminação',
        requirement: 'Localização segura, sem riscos de contaminação',
        details: [
          'Distância adequada de esgoto aberto',
          'Longe de lixões e depósitos de lixo',
          'Sem proximidade a hospitais ou áreas de risco',
          'Acesso sem obstáculos para entrega de alimentos',
        ],
      },
      {
        id: 'rdc216-1-2',
        category: '1. INSTALAÇÕES',
        itemNumber: 2,
        title: 'Estrutura do Prédio e Acabamento',
        description: 'Paredes, pisos e tetos devem estar em perfeitas condições',
        requirement: 'Sem rachaduras, umidade, mofo ou infiltrações',
        details: [
          'Paredes lisas e laváveis',
          'Pisos antiderrapantes e sem buracos',
          'Tetos sem manchas ou deterioração',
          'Ausência de mofo e infiltrações',
          'Vedação adequada contra pragas',
        ],
      },
      {
        id: 'rdc216-1-3',
        category: '1. INSTALAÇÕES',
        itemNumber: 3,
        title: 'Ventilação e Iluminação',
        description: 'Ambiente com ventilação adequada e iluminação suficiente',
        requirement: 'Ventilação adequada, sem odores desagradáveis. Iluminação mínima de 500 lux',
        details: [
          'Ventilação natural ou artificial adequada',
          'Ausência de odores desagradáveis',
          'Iluminação mínima de 500 lux nas áreas de trabalho',
          'Lâmpadas protegidas contra quebras',
          'Exaustores funcionando corretamente',
        ],
      },
      {
        id: 'rdc216-1-4',
        category: '1. INSTALAÇÕES',
        itemNumber: 4,
        title: 'Limpeza e Higiene Geral',
        description: 'Todas as dependências devem estar limpas e higienizadas',
        requirement: 'Limpeza diária, sem sujidades, poeiras ou resíduos',
        details: [
          'Ausência de poeira em superfícies elevadas',
          'Ausência de teia de aranha',
          'Pisos limpos e secos',
          'Ausência de gordura acumulada',
          'Ausência de resíduos de alimentos',
        ],
      },
      {
        id: 'rdc216-1-5',
        category: '1. INSTALAÇÕES',
        itemNumber: 5,
        title: 'Controle de Temperatura',
        description: 'Temperatura adequada no ambiente para preservação de alimentos',
        requirement: 'Temperatura entre 12-25°C em áreas de manipulação',
        details: [
          'Termômetros em locais visíveis',
          'Registros de temperatura diários',
          'Uso de ar condicionado em dias quentes',
          'Ausência de calor excessivo perto de equipamentos',
        ],
      },
    ],
  },
  {
    id: 'rdc216-2',
    name: '2. EQUIPAMENTOS E UTENSÍLIOS',
    description: 'Condição, limpeza e manutenção de equipamentos e utensílios',
    items: [
      {
        id: 'rdc216-2-1',
        category: '2. EQUIPAMENTOS',
        itemNumber: 1,
        title: 'Equipamentos Refrigerados',
        description: 'Geladeiras, freezers e câmaras devem estar em perfeito funcionamento',
        requirement: 'Temperatura adequada: 0-4°C (refrigerador), -12°C ou menos (freezer)',
        details: [
          'Termômetro com leitura fácil',
          'Limpeza interna regularmente',
          'Ausência de gelo excessivo',
          'Alimentos organizados por tipo',
          'Vedação adequada da porta',
          'Manutenção preventiva registrada',
        ],
      },
      {
        id: 'rdc216-2-2',
        category: '2. EQUIPAMENTOS',
        itemNumber: 2,
        title: 'Fogão e Fornos',
        description: 'Equipamentos de cocção devem estar funcionando corretamente',
        requirement: 'Aquecimento uniforme, sem vazamentos',
        details: [
          'Funcionamento adequado de queimadores',
          'Limpeza externa e interna',
          'Ausência de vazamento de gás',
          'Manutenção preventiva em dia',
          'Disponibilidade de extintor de incêndio próximo',
        ],
      },
      {
        id: 'rdc216-2-3',
        category: '2. EQUIPAMENTOS',
        itemNumber: 3,
        title: 'Utensílios de Trabalho',
        description: 'Facas, tábuas, panelas devem estar em bom estado e higienizados',
        requirement: 'Sem ferrugem, trincas ou acúmulo de sujidades',
        details: [
          'Ausência de ferrugem',
          'Ausência de trincas ou lascas',
          'Higienização adequada',
          'Armazenamento apropriado',
          'Tábuas de corte separadas por alimento',
        ],
      },
      {
        id: 'rdc216-2-4',
        category: '2. EQUIPAMENTOS',
        itemNumber: 4,
        title: 'Pias e Lavatórios',
        description: 'Pias devem estar em funcionamento e apropriadas para higienização',
        requirement: 'Água quente e fria, sabonete e toalha descartável',
        details: [
          'Água quente e fria',
          'Sabonete de boa qualidade',
          'Toalha descartável disponível',
          'Ralo sem obstruções',
          'Canos sem vazamentos',
          'Altura adequada para higiene',
        ],
      },
      {
        id: 'rdc216-2-5',
        category: '2. EQUIPAMENTOS',
        itemNumber: 5,
        title: 'Escada Rolante de Alimentos',
        description: 'Balança deve estar calibrada e em funcionamento',
        requirement: 'Calibração atualizada, leitura correta',
        details: [
          'Calibração em dia',
          'Limpeza regular',
          'Funcionamento adequado',
          'Ausência de poeira nos displays',
        ],
      },
    ],
  },
  {
    id: 'rdc216-3',
    name: '3. CONTROLE DE PRAGAS',
    description: 'Medidas preventivas e de controle de insetos e roedores',
    items: [
      {
        id: 'rdc216-3-1',
        category: '3. PRAGAS',
        itemNumber: 1,
        title: 'Evidência de Pragas',
        description: 'Ausência de sinais de infestação por insetos ou roedores',
        requirement: 'Zero evidência de pragas',
        details: [
          'Ausência de fezes de roedores',
          'Ausência de insetos vivos ou mortos',
          'Ausência de teias de aranha',
          'Ausência de ovos ou larvas',
          'Ausência de odor típico de infestação',
        ],
      },
      {
        id: 'rdc216-3-2',
        category: '3. PRAGAS',
        itemNumber: 2,
        title: 'Medidas Preventivas',
        description: 'Implementação de medidas para evitar infestação',
        requirement: 'Barreiras físicas e sanitárias',
        details: [
          'Telas nas janelas',
          'Vedação de portas',
          'Ausência de buracos nas paredes',
          'Recipientes de lixo com tampa',
          'Armazenamento adequado de alimentos',
        ],
      },
      {
        id: 'rdc216-3-3',
        category: '3. PRAGAS',
        itemNumber: 3,
        title: 'Monitoramento',
        description: 'Monitoramento regular e registros de controle',
        requirement: 'Inspeção visual diária, registros de controle',
        details: [
          'Inspeção visual frequente',
          'Registros de inspeção',
          'Registros de dedetização',
          'Contrato com empresa especializada',
          'Frequência de controle adequada',
        ],
      },
    ],
  },
  {
    id: 'rdc216-4',
    name: '4. ÁGUA E ESGOTO',
    description: 'Qualidade e armazenamento de água, tratamento de esgoto',
    items: [
      {
        id: 'rdc216-4-1',
        category: '4. ÁGUA',
        itemNumber: 1,
        title: 'Qualidade da Água',
        description: 'Água potável ou encanada de boa qualidade',
        requirement: 'Análise de potabilidade em dia',
        details: [
          'Análise microbiológica atualizada',
          'Análise físico-química',
          'Ausência de turbidez',
          'Cloro residual adequado',
          'pH adequado',
        ],
      },
      {
        id: 'rdc216-4-2',
        category: '4. ÁGUA',
        itemNumber: 2,
        title: 'Armazenamento de Água',
        description: 'Água armazenada em recipientes adequados',
        requirement: 'Reservatório limpo e protegido',
        details: [
          'Reservatório coberto',
          'Limpeza regular (semestral)',
          'Ausência de vazamentos',
          'Acesso restrito',
          'Identificação clara de água potável',
        ],
      },
      {
        id: 'rdc216-4-3',
        category: '4. ÁGUA',
        itemNumber: 3,
        title: 'Encanação',
        description: 'Tubulações sem problemas de corrosão ou vazamento',
        requirement: 'Canos em bom estado',
        details: [
          'Ausência de vazamentos',
          'Ausência de corrosão',
          'Encanação elevada quando possível',
          'Manutenção regularmente',
        ],
      },
      {
        id: 'rdc216-4-4',
        category: '4. ESGOTO',
        itemNumber: 4,
        title: 'Sistema de Esgoto',
        description: 'Esgoto adequadamente canalizado e tratado',
        requirement: 'Conexão com rede de esgoto ou fossa séptica',
        details: [
          'Ligação com rede pública',
          'Fossa séptica em bom estado',
          'Ralos sem obstruções',
          'Ausência de odor de esgoto',
          'Canaletas adequadas',
        ],
      },
    ],
  },
  {
    id: 'rdc216-5',
    name: '5. RESÍDUOS E LIXO',
    description: 'Gerenciamento de resíduos e disposição de lixo',
    items: [
      {
        id: 'rdc216-5-1',
        category: '5. RESÍDUOS',
        itemNumber: 1,
        title: 'Acondicionamento de Lixo',
        description: 'Lixo armazenado em recipientes apropriados',
        requirement: 'Recipientes com tampa, impermeáveis',
        details: [
          'Recipientes com tampa',
          'Material impermeável',
          'Capacidade adequada',
          'Fácil limpeza',
          'Separação por tipo de resíduo',
        ],
      },
      {
        id: 'rdc216-5-2',
        category: '5. RESÍDUOS',
        itemNumber: 2,
        title: 'Frequência de Coleta',
        description: 'Lixo coletado regularmente',
        requirement: 'Coleta diária em dias quentes, mínimo 2x por semana',
        details: [
          'Coleta frequente',
          'Não deve acumular',
          'Ausência de odor',
          'Recipientes não transbordam',
        ],
      },
      {
        id: 'rdc216-5-3',
        category: '5. RESÍDUOS',
        itemNumber: 3,
        title: 'Óleo de Cozinha',
        description: 'Óleo usado armazenado adequadamente',
        requirement: 'Recipiente específico, protegido',
        details: [
          'Recipiente próprio com tampa',
          'Armazenamento seguro',
          'Destinação apropriada',
          'Ausência de vazamento',
        ],
      },
    ],
  },
  {
    id: 'rdc216-6',
    name: '6. MANIPULADORES E SAÚDE',
    description: 'Higiene pessoal, saúde e treinamento dos manipuladores',
    items: [
      {
        id: 'rdc216-6-1',
        category: '6. MANIPULADORES',
        itemNumber: 1,
        title: 'Higiene Pessoal',
        description: 'Manipuladores mantêm higiene adequada',
        requirement: 'Mãos limpas, unhas cortadas, sem adornos',
        details: [
          'Mãos sempre limpas',
          'Unhas cortadas e sem esmalte',
          'Sem anéis, pulseiras ou relógios',
          'Asseio pessoal adequado',
          'Ausência de ferimentos expostos',
        ],
      },
      {
        id: 'rdc216-6-2',
        category: '6. MANIPULADORES',
        itemNumber: 2,
        title: 'Vestuário e EPIs',
        description: 'Uso de uniforme apropriado e de bom estado',
        requirement: 'Uniforme limpo, toca e avental',
        details: [
          'Uniforme limpo e em bom estado',
          'Toca ou boné',
          'Avental quando necessário',
          'Sapato apropriado (fechado)',
          'Luvas quando necessário',
        ],
      },
      {
        id: 'rdc216-6-3',
        category: '6. MANIPULADORES',
        itemNumber: 3,
        title: 'Saúde e Doenças',
        description: 'Manipuladores afastados quando doentes',
        requirement: 'Sem sintomas de doenças transmissíveis',
        details: [
          'Sem diarréia',
          'Sem vômitos',
          'Sem ferimentos',
          'Sem infecções respiratórias',
          'Registros de afastamento',
        ],
      },
      {
        id: 'rdc216-6-4',
        category: '6. MANIPULADORES',
        itemNumber: 4,
        title: 'Treinamento',
        description: 'Manipuladores treinados em higiene e segurança',
        requirement: 'Treinamento anual obrigatório',
        details: [
          'Capacitação inicial',
          'Treinamento anual',
          'Certificados de treinamento',
          'Conhecimento de boas práticas',
          'Conhecimento de APPCC',
        ],
      },
    ],
  },
  {
    id: 'rdc216-7',
    name: '7. MATÉRIAS-PRIMAS',
    description: 'Seleção, armazenamento e controle de qualidade',
    items: [
      {
        id: 'rdc216-7-1',
        category: '7. MATÉRIAS-PRIMAS',
        itemNumber: 1,
        title: 'Procedência e Qualidade',
        description: 'Alimentos de origem confiável e boa qualidade',
        requirement: 'Fornecedores registrados e confiáveis',
        details: [
          'Fornecedores conhecidos',
          'Documentação de origem',
          'Inspeção visual na entrega',
          'Registro de fornecedores',
          'Ausência de produtos vencidos',
        ],
      },
      {
        id: 'rdc216-7-2',
        category: '7. MATÉRIAS-PRIMAS',
        itemNumber: 2,
        title: 'Armazenamento de Alimentos',
        description: 'Alimentos armazenados adequadamente',
        requirement: 'Organização por tipo, temperatura correta',
        details: [
          'Alimentos separados por tipo',
          'Identificação clara de produtos',
          'Temperatura adequada',
          'Ausência de contaminação cruzada',
          'Sistema FIFO (primeiro que entra, primeiro que sai)',
        ],
      },
      {
        id: 'rdc216-7-3',
        category: '7. MATÉRIAS-PRIMAS',
        itemNumber: 3,
        title: 'Prazos de Validade',
        description: 'Produtos não vencidos, controle adequado',
        requirement: 'Verificação regular de validade',
        details: [
          'Data de validade verificada',
          'Produtos vencidos removidos',
          'Sistema de rotação de estoque',
          'Registros de verificação',
        ],
      },
    ],
  },
  {
    id: 'rdc216-8',
    name: '8. PREPARAÇÃO E MANIPULAÇÃO',
    description: 'Processo de preparação, cozimento e distribuição',
    items: [
      {
        id: 'rdc216-8-1',
        category: '8. PREPARAÇÃO',
        itemNumber: 1,
        title: 'Separação de Alimentos',
        description: 'Separação de alimentos para evitar contaminação cruzada',
        requirement: 'Alimentos crus separados de cozidos',
        details: [
          'Alimentos crus separados de cozidos',
          'Tábuas de corte diferentes por tipo',
          'Utensílios diferentes para alimentos diferentes',
          'Áreas de trabalho separadas quando possível',
        ],
      },
      {
        id: 'rdc216-8-2',
        category: '8. PREPARAÇÃO',
        itemNumber: 2,
        title: 'Higienização de Alimentos',
        description: 'Frutas e verduras higienizadas adequadamente',
        requirement: 'Lavagem em água corrente e hipoclorito',
        details: [
          'Lavagem em água corrente',
          'Uso de hipoclorito (10 minutos)',
          'Enxague final',
          'Ausência de sujidades',
        ],
      },
      {
        id: 'rdc216-8-3',
        category: '8. PREPARAÇÃO',
        itemNumber: 3,
        title: 'Temperaturas de Cozimento',
        description: 'Alimentos cozidos em temperaturas adequadas',
        requirement: 'Carnes 75°C, aves 82°C, peixes 65°C',
        details: [
          'Termômetro de alimento disponível',
          'Verificação de temperatura',
          'Registros de temperatura',
          'Tempo adequado de cozimento',
        ],
      },
      {
        id: 'rdc216-8-4',
        category: '8. PREPARAÇÃO',
        itemNumber: 4,
        title: 'Resfriamento de Alimentos',
        description: 'Alimentos resfriados rapidamente quando necessário',
        requirement: 'De 60°C a 21°C em até 2 horas',
        details: [
          'Resfriamento rápido',
          'Uso de banho de gelo',
          'Registros de resfriamento',
          'Armazenamento correto após resfriamento',
        ],
      },
    ],
  },
  {
    id: 'rdc216-9',
    name: '9. DOCUMENTAÇÃO E REGISTROS',
    description: 'Procedimentos documentados e registros mantidos',
    items: [
      {
        id: 'rdc216-9-1',
        category: '9. DOCUMENTAÇÃO',
        itemNumber: 1,
        title: 'Plano de Higienização',
        description: 'Plano escrito de higienização e limpeza',
        requirement: 'Documento formal, atualizado',
        details: [
          'Responsáveis designados',
          'Frequência de limpeza',
          'Produtos utilizados',
          'Checklist de limpeza',
        ],
      },
      {
        id: 'rdc216-9-2',
        category: '9. DOCUMENTAÇÃO',
        itemNumber: 2,
        title: 'POPs - Procedimentos Operacionais',
        description: 'Procedimentos escritos de operação e segurança',
        requirement: 'Documentos disponíveis para consulta',
        details: [
          'Higiêne pessoal',
          'Preparação de alimentos',
          'Limpeza e desinfecção',
          'Controle de pragas',
          'Saúde dos manipuladores',
        ],
      },
      {
        id: 'rdc216-9-3',
        category: '9. DOCUMENTAÇÃO',
        itemNumber: 3,
        title: 'Registros de Controle',
        description: 'Registros de temperatura, limpeza, treinamento',
        requirement: 'Mantidos atualizados e organizados',
        details: [
          'Registros de temperatura',
          'Registros de limpeza',
          'Registros de treinamento',
          'Registros de manutenção',
          'Registros de controle de pragas',
        ],
      },
    ],
  },
];

// RDC 275 - INDÚSTRIA DE ALIMENTOS
export const RDC275_CATEGORIES: ChecklistCategory[] = [
  {
    id: 'rdc275-1',
    name: '1. LOCALIZAÇÃO E ESTRUTURA',
    description: 'Localização apropriada, estrutura adequada e condições sanitárias',
    items: [
      {
        id: 'rdc275-1-1',
        category: '1. LOCALIZAÇÃO',
        itemNumber: 1,
        title: 'Localização da Indústria',
        description: 'Localização adequada, sem riscos ambientais',
        requirement: 'Longe de fontes de contaminação',
        details: [
          'Distância de esgoto aberto',
          'Distância de lixões',
          'Sem riscos de alagamento',
          'Acesso adequado para veículos',
          'Sem proximidade a indústrias poluentes',
        ],
      },
      {
        id: 'rdc275-1-2',
        category: '1. LOCALIZAÇÃO',
        itemNumber: 2,
        title: 'Estrutura e Acabamento',
        description: 'Paredes, pisos, tetos em perfeitas condições',
        requirement: 'Sem danos, limpável e desinfetável',
        details: [
          'Paredes impermeáveis e lisas',
          'Pisos antiderrapantes',
          'Tetos sem infiltrações',
          'Cantos e junções selados',
          'Material apropriado para alimentos',
        ],
      },
      {
        id: 'rdc275-1-3',
        category: '1. LOCALIZAÇÃO',
        itemNumber: 3,
        title: 'Fluxo de Produção',
        description: 'Layout adequado para evitar contaminação cruzada',
        requirement: 'Separação de áreas de acordo com risco',
        details: [
          'Área de recebimento separada',
          'Áreas de manipulação organizadas',
          'Área de expedição separada',
          'Fluxo unidirecional quando possível',
          'Barreira entre áreas de risco',
        ],
      },
      {
        id: 'rdc275-1-4',
        category: '1. LOCALIZAÇÃO',
        itemNumber: 4,
        title: 'Ventilação e Climatização',
        description: 'Ventilação adequada, temperatura e umidade controladas',
        requirement: 'Pressão positiva em áreas críticas',
        details: [
          'Filtros de ar adequados',
          'Temperatura controlada',
          'Umidade adequada ao produto',
          'Ausência de odores',
          'Manutenção de filtros',
        ],
      },
    ],
  },
  {
    id: 'rdc275-2',
    name: '2. EQUIPAMENTOS E UTENSÍLIOS',
    description: 'Equipamentos industriais, manutenção e higienização',
    items: [
      {
        id: 'rdc275-2-1',
        category: '2. EQUIPAMENTOS',
        itemNumber: 1,
        title: 'Capacidade e Adequação',
        description: 'Equipamentos com capacidade adequada ao volume de produção',
        requirement: 'Equipamentos apropriados para o processo',
        details: [
          'Capacidade suficiente',
          'Design apropriado',
          'Facilidade de limpeza',
          'Ausência de sobrecarga',
        ],
      },
      {
        id: 'rdc275-2-2',
        category: '2. EQUIPAMENTOS',
        itemNumber: 2,
        title: 'Manutenção Preventiva',
        description: 'Programa de manutenção regular implementado',
        requirement: 'Registros de manutenção em dia',
        details: [
          'Cronograma de manutenção',
          'Registros detalhados',
          'Peças de reposição disponíveis',
          'Calibração de equipamentos',
          'Reparo imediato de problemas',
        ],
      },
      {
        id: 'rdc275-2-3',
        category: '2. EQUIPAMENTOS',
        itemNumber: 3,
        title: 'Higiene de Equipamentos',
        description: 'Equipamentos limpos e desinfetados regularmente',
        requirement: 'Procedimento de limpeza documentado',
        details: [
          'Limpeza diária/conforme necessário',
          'Desinfecção apropriada',
          'Ausência de resíduos',
          'Registros de limpeza',
        ],
      },
      {
        id: 'rdc275-2-4',
        category: '2. EQUIPAMENTOS',
        itemNumber: 4,
        title: 'Instrumentos de Medição',
        description: 'Termômetros, pHmetros, densímetros calibrados',
        requirement: 'Calibração em dia, rastreável',
        details: [
          'Calibração obrigatória',
          'Certificado de calibração',
          'Frequência adequada',
          'Rastreabilidade metrológica',
        ],
      },
    ],
  },
  {
    id: 'rdc275-3',
    name: '3. CONTROLE DE QUALIDADE',
    description: 'Monitoramento, análises e controle de qualidade',
    items: [
      {
        id: 'rdc275-3-1',
        category: '3. QUALIDADE',
        itemNumber: 1,
        title: 'Análises Microbiológicas',
        description: 'Testes de microrganismos em matérias-primas e produtos',
        requirement: 'Programa de análises implementado',
        details: [
          'Contagem total de microrganismos',
          'Detecção de patógenos',
          'Coliformes totais e fecais',
          'Frequência de análise',
          'Laboratório credenciado',
        ],
      },
      {
        id: 'rdc275-3-2',
        category: '3. QUALIDADE',
        itemNumber: 2,
        title: 'Análises Físico-Químicas',
        description: 'Testes de composição e propriedades do produto',
        requirement: 'Análise por lote de produção',
        details: [
          'Umidade',
          'Gordura',
          'Proteínas',
          'pH',
          'Acidez',
          'Contaminantes',
        ],
      },
      {
        id: 'rdc275-3-3',
        category: '3. QUALIDADE',
        itemNumber: 3,
        title: 'Testes de Estabilidade',
        description: 'Verificação de estabilidade do produto ao longo do tempo',
        requirement: 'Programa de estabilidade implementado',
        details: [
          'Teste de prateleira',
          'Teste de temperatura',
          'Verificação de alterações',
          'Validade confirmada',
        ],
      },
    ],
  },
  {
    id: 'rdc275-4',
    name: '4. MATÉRIAS-PRIMAS E ADITIVOS',
    description: 'Seleção, armazenamento e controle de ingredientes',
    items: [
      {
        id: 'rdc275-4-1',
        category: '4. MATÉRIAS',
        itemNumber: 1,
        title: 'Aprovação de Fornecedores',
        description: 'Fornecedores analisados e aprovados',
        requirement: 'Programa de aprovação de fornecedores',
        details: [
          'Avaliação de capacidade',
          'Certificações verificadas',
          'Documentação em dia',
          'Auditorias periódicas',
          'Re-aprovação conforme necessário',
        ],
      },
      {
        id: 'rdc275-4-2',
        category: '4. MATÉRIAS',
        itemNumber: 2,
        title: 'Recebimento e Inspeção',
        description: 'Inspeção na recepção de todas as matérias-primas',
        requirement: 'Inspeção documentada',
        details: [
          'Verificação visual',
          'Análise de documentação',
          'Testes simples quando necessário',
          'Rejeição de não-conformes',
          'Quarentena de suspeitos',
        ],
      },
      {
        id: 'rdc275-4-3',
        category: '4. MATÉRIAS',
        itemNumber: 3,
        title: 'Armazenamento',
        description: 'Armazenamento adequado de matérias-primas',
        requirement: 'Temperatura, umidade e higiene controladas',
        details: [
          'Temperatura adequada',
          'Umidade relativa apropriada',
          'Proteção contra pragas',
          'Organização por tipo',
          'FIFO (primeiro que entra)',
        ],
      },
      {
        id: 'rdc275-4-4',
        category: '4. MATÉRIAS',
        itemNumber: 4,
        title: 'Aditivos e Coadjuvantes',
        description: 'Uso autorizado de aditivos alimentares',
        requirement: 'Apenas aditivos permitidos pela legislação',
        details: [
          'Aprovação legal confirmada',
          'Limite de uso respeitado',
          'Documentação em dia',
          'Rastreabilidade completa',
        ],
      },
    ],
  },
  {
    id: 'rdc275-5',
    name: '5. PROCESSO DE FABRICAÇÃO',
    description: 'Controle do processo de produção e operações',
    items: [
      {
        id: 'rdc275-5-1',
        category: '5. PROCESSO',
        itemNumber: 1,
        title: 'Procedimentos de Fabricação',
        description: 'Procedimentos escritos e seguidos rigorosamente',
        requirement: 'Documentação completa do processo',
        details: [
          'Fluxograma de processo',
          'Instruções por etapa',
          'Responsabilidades designadas',
          'Parâmetros críticos',
          'Frequência de verificação',
        ],
      },
      {
        id: 'rdc275-5-2',
        category: '5. PROCESSO',
        itemNumber: 2,
        title: 'Monitoramento de Processo',
        description: 'Monitoramento contínuo dos parâmetros de processo',
        requirement: 'Registros de todas as verificações',
        details: [
          'Temperatura monitorada',
          'Tempo de processo verificado',
          'Registros contínuos',
          'Ações corretivas se necessário',
          'Responsável designado',
        ],
      },
      {
        id: 'rdc275-5-3',
        category: '5. PROCESSO',
        itemNumber: 3,
        title: 'Validação de Processo',
        description: 'Validação que o processo alcança os objetivos',
        requirement: 'Estudo formal de validação',
        details: [
          'Segurança microbiológica comprovada',
          'Qualidade mantida',
          'Reprodutibilidade verificada',
          'Documentação de validação',
        ],
      },
      {
        id: 'rdc275-5-4',
        category: '5. PROCESSO',
        itemNumber: 4,
        title: 'Produto Não-Conforme',
        description: 'Procedimento para produto fora de especificação',
        requirement: 'Procedimento estabelecido',
        details: [
          'Identificação clara',
          'Armazenamento separado',
          'Investigação de causa',
          'Decisão de destinação',
          'Registros de ação',
        ],
      },
    ],
  },
  {
    id: 'rdc275-6',
    name: '6. RASTREABILIDADE',
    description: 'Sistema de rastreabilidade e recall',
    items: [
      {
        id: 'rdc275-6-1',
        category: '6. RASTREABILIDADE',
        itemNumber: 1,
        title: 'Sistema de Rastreabilidade',
        description: 'Capacidade de rastrear produto do fornecedor até consumidor',
        requirement: 'Sistema documentado e funcional',
        details: [
          'Identificação por lote',
          'Registro de data/hora de produção',
          'Ingredientes rastreáveis',
          'Histórico completo',
          'Testes periódicos do sistema',
        ],
      },
      {
        id: 'rdc275-6-2',
        category: '6. RASTREABILIDADE',
        itemNumber: 2,
        title: 'Recall',
        description: 'Procedimento para retirada rápida de produto do mercado',
        requirement: 'Plano de recall estabelecido',
        details: [
          'Procedimento escrito',
          'Responsáveis designados',
          'Contatos de clientes',
          'Testes práticos periódicos',
          'Registros de ações',
        ],
      },
    ],
  },
  {
    id: 'rdc275-7',
    name: '7. MANIPULADORES E HIGIENE',
    description: 'Treinamento, saúde e higiene pessoal dos operários',
    items: [
      {
        id: 'rdc275-7-1',
        category: '7. MANIPULADORES',
        itemNumber: 1,
        title: 'Treinamento em Segurança',
        description: 'Treinamento em segurança alimentar e higiene',
        requirement: 'Treinamento obrigatório para todos',
        details: [
          'Programa formal de treinamento',
          'Capacitação na admissão',
          'Reciclagem periódica (anual)',
          'Avaliação de conhecimento',
          'Certificados de treinamento',
        ],
      },
      {
        id: 'rdc275-7-2',
        category: '7. MANIPULADORES',
        itemNumber: 2,
        title: 'Controle de Saúde',
        description: 'Verificação de saúde dos manipuladores',
        requirement: 'Exames médicos periódicos',
        details: [
          'Exame de admissão',
          'Exame periódico (anual)',
          'Teste de tuberculose',
          'Teste de parasitas',
          'Registro médico confidencial',
        ],
      },
      {
        id: 'rdc275-7-3',
        category: '7. MANIPULADORES',
        itemNumber: 3,
        title: 'Higiene e Vestuário',
        description: 'Uniforme adequado e higiene pessoal mantida',
        requirement: 'Uniforme limpo, toca, sapato fechado',
        details: [
          'Uniforme apropriado',
          'Toca/boné (áreas críticas)',
          'Sapato fechado',
          'Avental quando necessário',
          'Luvas (se necessário)',
          'Sem adornos',
        ],
      },
    ],
  },
  {
    id: 'rdc275-8',
    name: '8. EMBALAGEM E ROTULAGEM',
    description: 'Material de embalagem, rótulo e identificação',
    items: [
      {
        id: 'rdc275-8-1',
        category: '8. EMBALAGEM',
        itemNumber: 1,
        title: 'Qualidade da Embalagem',
        description: 'Embalagem apropriada e de boa qualidade',
        requirement: 'Embalagem protege o produto',
        details: [
          'Material apropriado',
          'Integridade verificada',
          'Ausência de contaminantes',
          'Armazenamento correto',
          'Ausência de dano',
        ],
      },
      {
        id: 'rdc275-8-2',
        category: '8. EMBALAGEM',
        itemNumber: 2,
        title: 'Rotulagem Correta',
        description: 'Rótulo com todas as informações obrigatórias',
        requirement: 'Conforme RDC 259/2002',
        details: [
          'Identificação do produto',
          'Lista de ingredientes',
          'Informação nutricional',
          'Validade clara',
          'Modo de conservação',
          'Lote identificado',
          'Contato da empresa',
        ],
      },
      {
        id: 'rdc275-8-3',
        category: '8. EMBALAGEM',
        itemNumber: 3,
        title: 'Armazenamento de Embalagens',
        description: 'Embalagens armazenadas adequadamente',
        requirement: 'Proteção contra contaminação',
        details: [
          'Local apropriado',
          'Protegido contra poeira',
          'Protegido contra pragas',
          'Temperaturas adequadas',
          'Organizado e identificado',
        ],
      },
    ],
  },
  {
    id: 'rdc275-9',
    name: '9. DOCUMENTAÇÃO E REGISTROS',
    description: 'Registros de produção, análises e procedimentos',
    items: [
      {
        id: 'rdc275-9-1',
        category: '9. DOCUMENTAÇÃO',
        itemNumber: 1,
        title: 'Manual de APPCC',
        description: 'Análise de Perigos e Pontos Críticos de Controle',
        requirement: 'Documento formal implementado',
        details: [
          'Análise de perigos',
          'Identificação de PCCs',
          'Limites críticos',
          'Monitoramento',
          'Ações corretivas',
          'Verificação',
        ],
      },
      {
        id: 'rdc275-9-2',
        category: '9. DOCUMENTAÇÃO',
        itemNumber: 2,
        title: 'Registros de Produção',
        description: 'Todos os lotes rastreados com registros completos',
        requirement: 'Registro detalhado de cada lote',
        details: [
          'Data e hora de produção',
          'Matérias-primas utilizadas',
          'Operador responsável',
          'Parâmetros de processo',
          'Problemas identificados',
        ],
      },
      {
        id: 'rdc275-9-3',
        category: '9. DOCUMENTAÇÃO',
        itemNumber: 3,
        title: 'Registros de Análises',
        description: 'Resultados de análises microbiológicas e físico-químicas',
        requirement: 'Registro de toda análise realizada',
        details: [
          'Data de análise',
          'Lote analisado',
          'Resultado obtido',
          'Comparação com limite',
          'Ações se não-conforme',
        ],
      },
    ],
  },
];
